CREATE TABLE TINDER.CHOICES (
                                         PERSON_ID INTEGER,
                                         SELECTED_ID INTEGER,
                                         PRIMARY KEY (PERSON_ID, SELECTED_ID)
);
CREATE UNIQUE INDEX I_CHOICES_ID ON TINDER.CHOICES (PERSON_ID, SELECTED_ID);
CREATE SEQUENCE TINDER.CHOICES_S;