INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10000, 'SIR', 'Иннокентiй', 'Я прiѣзжiй изъ Кавказа. Лѣть 22-хъ, брюнетъ, черные глаза, чернобровый, правильныя черты лица, рост выше среднего, красивой и представительной наружности, серьезный. Желаю, въ цѣляхъ выбора жены, спутницы жизни, познакомиться съ молоденькою, отъ 18 до 20-ти лѣть, интеллигентной, образованной, особой красавицей. Презрѣнному металлу нѣтъ мѣста. Обладаю солидным капиталомъ.', 'MADAM', 100200300, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\42119a35-b668-42f8-a597-b0db367aaf30.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10001, 'MADAM', 'Анна', 'За (совсѣмъ) старого дворянина, миллiонера выйду замужъ. Дворянка, 35 лѣть. Подробности въ перепискѣ. Москва. Леонтьевский пер., д.Хринковой', 'SIR', 110220330, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\d3ded4c5-f7c0-4a47-afb6-ddd76a6a3ab9.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10002, 'SIR', 'Иванъ', 'На разсвѣiѣ красивой жизни. Иду, навстрѣчу изящной чарующей юности. Кто хочетѣ встрѣтить встающее солнце счастья вмѣстѣ съ молодымъ, талантливымъ, обеспеченнымъ?', 'ALL', 111222333, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\15ed7197-37a7-4933-bd22-4f4b71b25b86.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10003, 'SIR', 'Артуръ', 'Молодой миллiонеръ. (60,000 годового дохода), красивый, интеллигентный, совершенно свободный и одинокий, хотѣлъ бы жениться на дѣвушкѣ не старше 20 лѣтъ, брюнеткѣ или шатенкѣ, среднего роста, интеллигентной, изящной. Желательна карточка.', 'MADAM', 111111111, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\7fcda914-0e32-4b5b-b234-ad4090daa720.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10004, 'SIR', 'Александеръ', 'Серьезно. Не ищу богатства, ищу жизни, отзовись женщина, желающая жизни: барышня, вдова или женщина, влекущая разбитую жизнъ; вѣроисповѣданiе безразлично. Я бѣдный, но не ищу богатства, ищу жизни, и выше всего цѣню жизнь', 'MADAM', 111111112, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\da4b4c6a-333b-4667-a727-12bec591f413.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10005, 'SIR', 'Ярославъ', 'Белорусъ. Шатенъ, 30 лѣтъ, скромный, трезвый, хорошего характера, съ добрымъ, любящимъ сердцемъ, необезпеченъ, желалъ бы познакомиться и жениться на особѣ, несколько обеспеченной, которая оказала бы денежную помощь для поступленiя въ члены артели.', 'MADAM', 111111113, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\a2eacfc3-88c3-4d27-8263-b97d79db2db8.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10006, 'MADAM', 'Светлана', 'Явись ко мнѣ ьужемъ, другомъ, товарищемъ, не моложе 40 лѣтъ, состоятельный, добрый человѣкъ. Осчастливлю, согрѣю твою одинокую жизнь. Вдова, 32 лѣтъ, интеллигентная армянка высоконравная, интересная. Жажду идеальной любви. Томлюсь душевнымъ одиночествомъ.', 'SIR', 111111114, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\014d89ab-ecd9-4e66-82f7-5da7730c4054.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10007, 'SIR', 'Ѳёдоръ', 'Мечты потомственного дворянина, 36 лѣтъ, безъ личныхъ средствъ, зовутъ на бракъ съ нимъ дѣвушку или вдову высших круговъ, близкую ему по духу: религiозную, правыхъ взглядовъ, мягкого, деликатного характера, сердечно относящуюся къ бѣднымъ, низшимъ, зависимымъ, любящую истинную благотворительность и тихую, мирную жизнь.', 'MADAM', 111111115, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\281b5bef-ec54-407d-9340-03dbd9b69423.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10008, 'SIR', 'Егоръ', 'Довольно переносить одиночество, ищу подругу жизни, чуткую натуру, помощницу в дѣлах и участницу в боготворении моих долголѣтних трудов. Кто откликнется на это объявленiе жалѣть не будет. Цѣль брак. Карточка желательна.', 'MADAM', 111111116, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\71d2197a-77e3-433f-b08d-80cffd5af3cf.jpg');
INSERT INTO tinder.persons (ID, GENDER, NAME, DESCRIPTION, SEARCH_TERM, USER_ID, BOT_STATE, IMAGE_PATH)
VALUES (10009, 'SIR', 'Игорь', 'На пожилой, больной или съ физическимъ недостаткомъ особѣ, желаетъ немедленно жениться, 28 л., съ хорошей наружностью, но только что потерявший зрѣнiе на один глазъ, образованный, имѣющiй прибыльное дѣло; для увеличенiя его желательно около 3 т. р. Прошу откликнуться для такой уютной жизни.', 'MADAM', 111111117, 'MENU', 'C:\Users\akassina\IdeaProjects\prerevolution-tinder\prerevolutionary-tinder-server\out\production\resources\images\3a48f322-6f03-45c9-86c3-803ca333bcd3.jpg');