package ru.digitalleague.prerevolutionarytinder.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import ru.digitalleague.prerevolutionarytinder.api.TranslateSlavonicService;

import javax.annotation.PostConstruct;
import java.util.HashMap;

import org.apache.commons.lang3.StringUtils;

@Component
@RequiredArgsConstructor
public class DefaultTranslateSlavonicService implements TranslateSlavonicService {
    String VOWELS = "АЕЁИОУЫЭЮЯЙаеёиоуыэюяй";
    String CONSTANTS = "БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ";

    private final HashMap<String, String> replaceSlavonic = new HashMap<>();

    @PostConstruct
    private void init() {
        replaceSlavonic.put("Агафья", "Агаѳья");
        replaceSlavonic.put("Анфим", "Анѳим");
        replaceSlavonic.put("Афанасий", "Аѳанасий");
        replaceSlavonic.put("Афина", "Аѳина");
        replaceSlavonic.put("Варфоломей", "Варѳоломей");
        replaceSlavonic.put("Голиаф", "Голиаѳ");
        replaceSlavonic.put("Евфимий", "Евѳимий");
        replaceSlavonic.put("Марфа", "Марѳа");
        replaceSlavonic.put("Матфей", "Матѳей");
        replaceSlavonic.put("Мефодий", "Меѳодий");
        replaceSlavonic.put("Нафанаил", "Наѳанаил");
        replaceSlavonic.put("Парфенон", "Парѳенон");
        replaceSlavonic.put("Пифагор", "Пиѳагор");
        replaceSlavonic.put("Руфь", "Руѳь");
        replaceSlavonic.put("Саваоф", "Саваоѳъ");
        replaceSlavonic.put("Тимофей", "Тимоѳей");
        replaceSlavonic.put("Эсфирь", "Эсѳирь");
        replaceSlavonic.put("Иудифь", "Іудиѳь");
        replaceSlavonic.put("Фаддей", "Ѳаддей");
        replaceSlavonic.put("Фекла", "Ѳекла");
        replaceSlavonic.put("Фемида", "Ѳемида");
        replaceSlavonic.put("Фемистокл", "Ѳемистоклъ");
        replaceSlavonic.put("Феодор", "Ѳеодоръ");
        replaceSlavonic.put("Фёдор", "Ѳёдоръ");
        replaceSlavonic.put("Федя", "Ѳедя");
        replaceSlavonic.put("Феодосий", "Ѳеодосій");
        replaceSlavonic.put("Федосий", "Ѳедосій");
        replaceSlavonic.put("Феодосия", "Ѳеодосія");
        replaceSlavonic.put("Феодот", "Ѳеодотъ");
        replaceSlavonic.put("Федот", "Ѳедотъ");
        replaceSlavonic.put("Феофан", "Ѳеофанъ");
        replaceSlavonic.put("Феофил", "Ѳеофилъ");
        replaceSlavonic.put("Ферапонт", "Ѳерапонтъ");
        replaceSlavonic.put("Фома", "Ѳома");
        replaceSlavonic.put("Фоминична", "Ѳоминична");

        replaceSlavonic.put("еда", "ѣда");
        replaceSlavonic.put("ем", "ѣм");
        replaceSlavonic.put("есть", "ѣсть");
        replaceSlavonic.put("обед", "обѣд");
        replaceSlavonic.put("обедня", "обѣдня");
        replaceSlavonic.put("сыроежка", "сыроѣжка");
        replaceSlavonic.put("сыроега", "сыроѣга");
        replaceSlavonic.put("медведь", "медвѣдь");
        replaceSlavonic.put("снедь", "снѣдь");
        replaceSlavonic.put("едкий ехать", "ѣдкий ѣхать");
        replaceSlavonic.put("езда", "ѣзда");
        replaceSlavonic.put("уезд", "уѣзд");
        replaceSlavonic.put("еду", "ѣду");
        replaceSlavonic.put("ездить", "ѣздить");
        replaceSlavonic.put("поезд", "поѣзд");
        replaceSlavonic.put("бег", "бѣг");
        replaceSlavonic.put("беглец", "бѣглец");
        replaceSlavonic.put("беженец", "бѣженец");
        replaceSlavonic.put("забегаловка", "забѣгаловка");
        replaceSlavonic.put("избегать", "избѣгать");
        replaceSlavonic.put("избежать", "избѣжать");
        replaceSlavonic.put("набег", "набѣг");
        replaceSlavonic.put("перебежчик", "перебѣжчик");
        replaceSlavonic.put("пробег", "пробѣг");
        replaceSlavonic.put("разбег", "разбѣг");
        replaceSlavonic.put("убежище", "убѣжище");
        replaceSlavonic.put("центробежная сила", "центробѣжная сила");
        replaceSlavonic.put("беда", "бѣда");
        replaceSlavonic.put("бедный", "бѣдный");
        replaceSlavonic.put("победить", "побѣдить");
        replaceSlavonic.put("убедить", "убѣдить");
        replaceSlavonic.put("убеждение", "убѣждение");
        replaceSlavonic.put("белый", "бѣлый");
        replaceSlavonic.put("бельё", "бѣльё");
        replaceSlavonic.put("белка", "бѣлка");
        replaceSlavonic.put("бельмо", "бѣльмо");
        replaceSlavonic.put("белуга", "бѣлуга");
        replaceSlavonic.put("бес", "бѣс");
        replaceSlavonic.put("бешеный", "бѣшеный");
        replaceSlavonic.put("обет", "обѣт");
        replaceSlavonic.put("обещать", "обѣщать");
        replaceSlavonic.put("веять", "вѣять");
        replaceSlavonic.put("веер", "вѣер");
        replaceSlavonic.put("ветер", "вѣтер");
        replaceSlavonic.put("ветвь", "вѣтвь");
        replaceSlavonic.put("веха", "вѣха");
        replaceSlavonic.put("ведать", "вѣдать");
        replaceSlavonic.put("веди", "вѣди");
        replaceSlavonic.put("весть", "вѣсть");
        replaceSlavonic.put("повесть", "повѣсть");
        replaceSlavonic.put("ведение", "вѣ́дѣние");
        replaceSlavonic.put("вежливый", "вѣжливый");
        replaceSlavonic.put("невежда", "невѣжда");
        replaceSlavonic.put("вежды", "вѣжды");
        replaceSlavonic.put("вежа", "вѣжа");
        replaceSlavonic.put("век", "вѣк");
        replaceSlavonic.put("вечный", "вѣчный");
        replaceSlavonic.put("увечить", "увѣчить");
        replaceSlavonic.put("веко", "вѣко");
        replaceSlavonic.put("венок", "вѣнок");
        replaceSlavonic.put("венец", "вѣнец");
        replaceSlavonic.put("вениквенок", "вѣниквѣнок");
        replaceSlavonic.put("веник", "вѣник");
        replaceSlavonic.put("вено", "вѣно");
        replaceSlavonic.put("вера", "вѣра");
        replaceSlavonic.put("вероятно", "вѣроятно");
        replaceSlavonic.put("суеверие", "суевѣрие");
        replaceSlavonic.put("вес", "вѣс");
        replaceSlavonic.put("вешать", "вѣшать");
        replaceSlavonic.put("повеса", "повѣса");
        replaceSlavonic.put("равновесие", "равновѣсие");
        replaceSlavonic.put("звезда", "звѣзда");
        replaceSlavonic.put("зверь", "звѣрь");
        replaceSlavonic.put("невеста", "невѣста");
        replaceSlavonic.put("ответ", "отвѣт");
        replaceSlavonic.put("совет", "совѣт");
        replaceSlavonic.put("привет", "привѣт");
        replaceSlavonic.put("завет", "завѣт");
        replaceSlavonic.put("вещать", "вѣщать");
        replaceSlavonic.put("вече", "вѣче");
        replaceSlavonic.put("свежий", "свѣжий");
        replaceSlavonic.put("свежеть", "свѣжѣть");
        replaceSlavonic.put("свет", "свѣт");
        replaceSlavonic.put("свеча", "свѣча");
        replaceSlavonic.put("просвещение", "просвѣщение");
        replaceSlavonic.put("светец", "свѣтец");
        replaceSlavonic.put("светёлка", "свѣтёлка");
        replaceSlavonic.put("Светлана", "Свѣтлана");
        replaceSlavonic.put("цвет", "цвѣт");
        replaceSlavonic.put("цветы", "цвѣты");
        replaceSlavonic.put("цвести", "цвѣсти");
        replaceSlavonic.put("человек", "человѣк");
        replaceSlavonic.put("человеческий", "человѣческий");
        replaceSlavonic.put("деть", "дѣть");
        replaceSlavonic.put("девать", "дѣвать");
        replaceSlavonic.put("одеть", "одѣть");
        replaceSlavonic.put("одевать", "одѣвать");
        replaceSlavonic.put("одеяло", "одѣяло");
        replaceSlavonic.put("одеяние", "одѣяние");
        replaceSlavonic.put("дело", "дѣло");
        replaceSlavonic.put("делать", "дѣлать");
        replaceSlavonic.put("действие", "дѣйствие");
        replaceSlavonic.put("неделя", "недѣля");
        replaceSlavonic.put("надеяться", "надѣяться");
        replaceSlavonic.put("свидетель", "свидѣтель");
        replaceSlavonic.put("дева", "дѣва");
        replaceSlavonic.put("девочка", "дѣвочка");
        replaceSlavonic.put("дед", "дѣд");
        replaceSlavonic.put("делить", "дѣлить");
        replaceSlavonic.put("предел", "предѣл");
        replaceSlavonic.put("дети", "дѣти");
        replaceSlavonic.put("детёныш", "дѣтёныш");
        replaceSlavonic.put("детка", "дѣтка");
        replaceSlavonic.put("детство", "дѣтство");
        replaceSlavonic.put("зевать", "зѣвать");
        replaceSlavonic.put("зев", "зѣв");
        replaceSlavonic.put("ротозей", "ротозѣй");
        replaceSlavonic.put("зело", "зѣло");
        replaceSlavonic.put("зеница", "зѣница");
        replaceSlavonic.put("зенки", "зѣнки");
        replaceSlavonic.put("левый", "лѣвый");
        replaceSlavonic.put("левша", "лѣвша");
        replaceSlavonic.put("лезть", "лѣзть");
        replaceSlavonic.put("лестница", "лѣстница");
        replaceSlavonic.put("облезлый ", "облѣзлый");
        replaceSlavonic.put("лекарь", "лѣкарь");
        replaceSlavonic.put("лечить", "лѣчить");
        replaceSlavonic.put("лекарство", "лѣкарство");
        replaceSlavonic.put("лень", "лѣнь");
        replaceSlavonic.put("ленивец", "лѣнивец");
        replaceSlavonic.put("ленивый", "лѣнивый");
        replaceSlavonic.put("лентяй", "лѣнтяй");
        replaceSlavonic.put("лепота", "лѣпота");
        replaceSlavonic.put("великолепный", "великолѣпный");
        replaceSlavonic.put("лепить", "лѣпить");
        replaceSlavonic.put("нелепый", "нелѣпый");
        replaceSlavonic.put("слепок", "слѣпок");
        replaceSlavonic.put("лес", "лѣс");
        replaceSlavonic.put("лесник", "лѣсник");
        replaceSlavonic.put("лесничий", "лѣсничий");
        replaceSlavonic.put("лесопилка", "лѣсопилка");
        replaceSlavonic.put("леший", "лѣший");
        replaceSlavonic.put("лето", "лѣто");
        replaceSlavonic.put("долголетие", "долголѣтие");
        replaceSlavonic.put("Летов", "Лѣтов");
        replaceSlavonic.put("летоисчисление", "лѣтоисчисление");
        replaceSlavonic.put("летописец", "лѣтописец");
        replaceSlavonic.put("летопись", "лѣтопись");
        replaceSlavonic.put("малолетка", "малолѣтка");
        replaceSlavonic.put("однолетка", "однолѣтка");
        replaceSlavonic.put("пятилетка", "пятилѣтка");
        replaceSlavonic.put("совершеннолетие", "совершеннолѣтие");
        replaceSlavonic.put("леха", "лѣха́");
        replaceSlavonic.put("бледный", "блѣдный");
        replaceSlavonic.put("железо", "желѣзо");
        replaceSlavonic.put("железняк", "желѣзняк");
        replaceSlavonic.put("калека", "калѣка");
        replaceSlavonic.put("калечить", "калѣчить");
        replaceSlavonic.put("клеть", "клѣть");
        replaceSlavonic.put("клетка", "клѣтка");
        replaceSlavonic.put("колено", "колѣно");
        replaceSlavonic.put("наколенник", "наколѣнник");
        replaceSlavonic.put("поколение", "поколѣние");
        replaceSlavonic.put("лелеять", "лелѣять");
        replaceSlavonic.put("млеть", "млѣть");
        replaceSlavonic.put("плен", "плѣн");
        replaceSlavonic.put("пленённый", "плѣнённый");
        replaceSlavonic.put("пленить", "плѣнить");
        replaceSlavonic.put("пленник", "плѣнник");
        replaceSlavonic.put("плесень", "плѣсень");
        replaceSlavonic.put("плешь", "плѣшь");
        replaceSlavonic.put("Плеханов", "Плѣханов");
        replaceSlavonic.put("полено", "полѣно");
        replaceSlavonic.put("след", "слѣд");
        replaceSlavonic.put("последователь", "послѣдователь");
        replaceSlavonic.put("последствие", "послѣдствие");
        replaceSlavonic.put("преследовать", "преслѣдовать");
        replaceSlavonic.put("следить", "слѣдить");
        replaceSlavonic.put("следопыт", "слѣдопыт");
        replaceSlavonic.put("слепой", "слѣпой");
        replaceSlavonic.put("телега", "телѣга");
        replaceSlavonic.put("тележный", "телѣжный");
        replaceSlavonic.put("тлен", "тлѣн");
        replaceSlavonic.put("тление", "тлѣние");
        replaceSlavonic.put("тленный", "тлѣнный");
        replaceSlavonic.put("хлеб", "хлѣб");
        replaceSlavonic.put("хлев", "хлѣв");
        replaceSlavonic.put("медь", "мѣдь");
        replaceSlavonic.put("медный", "мѣдный");
        replaceSlavonic.put("мел", "мѣл");
        replaceSlavonic.put("менять", "мѣнять");
        replaceSlavonic.put("изменник", "измѣнник");
        replaceSlavonic.put("непременно", "непремѣнно");
        replaceSlavonic.put("мера", "мѣра");
        replaceSlavonic.put("намерение", "намѣрение");
        replaceSlavonic.put("лицемер", "лицемѣр");
        replaceSlavonic.put("месяц", "мѣсяц");
        replaceSlavonic.put("месить", "мѣсить");
        replaceSlavonic.put("мешать", "мѣшать");
        replaceSlavonic.put("помеха", "помѣха");
        replaceSlavonic.put("место", "мѣсто");
        replaceSlavonic.put("мещанин", "мѣщанин");
        replaceSlavonic.put("помещик", "помѣщик");
        replaceSlavonic.put("наместник", "намѣстник");
        replaceSlavonic.put("метить", "мѣтить");
        replaceSlavonic.put("замечать", "замѣчать");
        replaceSlavonic.put("примечание", "примѣчание");
        replaceSlavonic.put("сметить", "смѣтить");
        replaceSlavonic.put("смета", "смѣта");
        replaceSlavonic.put("мех", "мѣх");
        replaceSlavonic.put("мешок", "мѣшок");
        replaceSlavonic.put("змей", "змѣй");
        replaceSlavonic.put("змея", "змѣя");
        replaceSlavonic.put("сметь", "смѣть");
        replaceSlavonic.put("смелый", "смѣлый");
        replaceSlavonic.put("смеяться", "смѣяться");
        replaceSlavonic.put("смех", "смѣх");
        replaceSlavonic.put("нега", "нѣга");
        replaceSlavonic.put("нежный", "нѣжный");
        replaceSlavonic.put("нежить", "нѣжить");
        replaceSlavonic.put("недра", "нѣдра");
        replaceSlavonic.put("внедрить", "внѣдрить");
        replaceSlavonic.put("немой", "нѣмой");
        replaceSlavonic.put("немец", "нѣмец");
        replaceSlavonic.put("нет", "нѣт");
        replaceSlavonic.put("отнекаться", "отнѣкаться");
        replaceSlavonic.put("гнев", "гнѣв");
        replaceSlavonic.put("гнедой", "гнѣдой");
        replaceSlavonic.put("гнездо", "гнѣздо");
        replaceSlavonic.put("загнетка", "загнѣтка");
        replaceSlavonic.put("снег", "снѣг");
        replaceSlavonic.put("снежный", "снѣжный");
        replaceSlavonic.put("мнение", "мнѣние");
        replaceSlavonic.put("сомнение", "сомнѣние");
        replaceSlavonic.put("сомневаться", "сомнѣваться");
        replaceSlavonic.put("петь", "пѣть");
        replaceSlavonic.put("песня", "пѣсня");
        replaceSlavonic.put("петух", "пѣтух");
        replaceSlavonic.put("пегий", "пѣгий");
        replaceSlavonic.put("пена", "пѣна");
        replaceSlavonic.put("пенязь", "пѣнязь");
        replaceSlavonic.put("пестовать", "пѣстовать");
        replaceSlavonic.put("пестун", "пѣхота");
        replaceSlavonic.put("пеший", "пѣший");
        replaceSlavonic.put("опешить", "опѣшить");
        replaceSlavonic.put("спеть", "спѣть");
        replaceSlavonic.put("спех", "спѣх");
        replaceSlavonic.put("спешить", "спѣшить");
        replaceSlavonic.put("успех", "успѣх");
        replaceSlavonic.put("реять", "рѣять");
        replaceSlavonic.put("река", "рѣка");
        replaceSlavonic.put("речь", "рѣчь");
        replaceSlavonic.put("наречие", "нарѣчие");
        replaceSlavonic.put("редкий", "рѣдкий");
        replaceSlavonic.put("редька", "рѣдька");
        replaceSlavonic.put("резать", "рѣзать");
        replaceSlavonic.put("резвый", "рѣзвый");
        replaceSlavonic.put("репа", "рѣпа");
        replaceSlavonic.put("репица", "рѣпица");
        replaceSlavonic.put("ресница", "рѣсница");
        replaceSlavonic.put("обретать", "обрѣтать");
        replaceSlavonic.put("обрести", "обрѣсти");
        replaceSlavonic.put("сретение", "срѣтение");
        replaceSlavonic.put("встречать", "встрѣчать");
        replaceSlavonic.put("прореха", "прорѣха");
        replaceSlavonic.put("решето", "рѣшето");
        replaceSlavonic.put("решётка", "рѣшётка");
        replaceSlavonic.put("решать", "рѣшать");
        replaceSlavonic.put("решить", "рѣшить");
        replaceSlavonic.put("грех", "грѣх");
        replaceSlavonic.put("грешный", "грѣшный");
        replaceSlavonic.put("зреть", "зрѣть");
        replaceSlavonic.put("созреть", "созрѣть");
        replaceSlavonic.put("зрелый", "зрѣлый");
        replaceSlavonic.put("зрение", "зрѣние");
        replaceSlavonic.put("крепкий", "крѣпкий");
        replaceSlavonic.put("крепиться", "крѣпиться");
        replaceSlavonic.put("орех", "орѣх");
        replaceSlavonic.put("преть", "прѣть");
        replaceSlavonic.put("прелый", "прѣлый");
        replaceSlavonic.put("прение", "прѣние");
        replaceSlavonic.put("пресный", "прѣсный");
        replaceSlavonic.put("свирепый", "свирѣпый");
        replaceSlavonic.put("свирель", "свирѣль");
        replaceSlavonic.put("стрела", "стрѣла");
        replaceSlavonic.put("стрелять", "стрѣлять");
        replaceSlavonic.put("стреха", "стрѣха");
        replaceSlavonic.put("застреха", "застрѣха");
        replaceSlavonic.put("хрен", "хрѣн");
        replaceSlavonic.put("сусек", "сусѣк");
        replaceSlavonic.put("сеять", "сѣять");
        replaceSlavonic.put("семя", "сѣмя");
        replaceSlavonic.put("север", "сѣвер");
        replaceSlavonic.put("седло", "сѣдло");
        replaceSlavonic.put("сесть", "сѣсть");
        replaceSlavonic.put("беседа", "бесѣда");
        replaceSlavonic.put("сосед", "сосѣд");
        replaceSlavonic.put("седой", "сѣдой");
        replaceSlavonic.put("седеть", "сѣдѣть");
        replaceSlavonic.put("секу", "сѣку");
        replaceSlavonic.put("сечь", "сѣчь");
        replaceSlavonic.put("сеча", "сѣча");
        replaceSlavonic.put("сечение", "сѣчение");
        replaceSlavonic.put("просека", "просѣка");
        replaceSlavonic.put("насекомое", "насѣкомое");
        replaceSlavonic.put("сень", "сѣнь");
        replaceSlavonic.put("осенять", "осѣнять");
        replaceSlavonic.put("сени", "сѣни");
        replaceSlavonic.put("сено", "сѣно");
        replaceSlavonic.put("серый", "сѣрый");
        replaceSlavonic.put("сера", "сѣра");
        replaceSlavonic.put("посетить", "посѣтить");
        replaceSlavonic.put("посещать", "посѣщать");
        replaceSlavonic.put("сетовать", "сѣтовать");
        replaceSlavonic.put("сеть", "сѣть");
        replaceSlavonic.put("сетка", "сѣтка");
        replaceSlavonic.put("стена", "стѣна");
        replaceSlavonic.put("застенок", "застѣнок");
        replaceSlavonic.put("застенчивый", "застѣнчивый");
        replaceSlavonic.put("стенгазета", "стѣнгазета");
        replaceSlavonic.put("тело", "тѣло");
        replaceSlavonic.put("мягкотелость", "мягкотѣлость");
        replaceSlavonic.put("растелешиться", "растѣлешиться");
        replaceSlavonic.put("тельняшка", "тѣльняшка");
        replaceSlavonic.put("тень", "тѣнь");
        replaceSlavonic.put("оттенок", "оттѣнок");
        replaceSlavonic.put("тенёк", "тѣнёк");
        replaceSlavonic.put("тесто", "тѣсто");
        replaceSlavonic.put("тесный", "тѣсный");
        replaceSlavonic.put("стеснять", "стѣснять");
        replaceSlavonic.put("стесняться", "стѣсняться");
        replaceSlavonic.put("теснить", "тѣснить");
        replaceSlavonic.put("тесниться", "тѣсниться");
        replaceSlavonic.put("затеять", "затѣять");
        replaceSlavonic.put("затея", "затѣя");
        replaceSlavonic.put("утеха", "утѣха");
        replaceSlavonic.put("потеха", "потѣха");
        replaceSlavonic.put("тешить", "тѣшить");
        replaceSlavonic.put("утешение", "утѣшение");
        replaceSlavonic.put("хер", "хѣр");
        replaceSlavonic.put("похерить", "похѣрить");
        replaceSlavonic.put("цевка", "цѣвка");
        replaceSlavonic.put("цевье", "цѣвье");
        replaceSlavonic.put("цевница", "цѣвница");
        replaceSlavonic.put("цедить", "цѣдить");
        replaceSlavonic.put("целый", "цѣлый");
        replaceSlavonic.put("исцелять", "исцѣлять");
        replaceSlavonic.put("целовать", "цѣловать");
        replaceSlavonic.put("поцелуй", "поцѣлуй");
        replaceSlavonic.put("цель", "цѣль");
        replaceSlavonic.put("целиться", "цѣлиться");
        replaceSlavonic.put("цена", "цѣна");
        replaceSlavonic.put("цепь", "цѣпь");
        replaceSlavonic.put("цеплять", "цѣплять");
        replaceSlavonic.put("цеп", "цѣп");
    }

    //todo написать тест
    @Override
    public String translate(String rus) {
        final String[] keys = replaceSlavonic.keySet().toArray(new String[0]);
        final String[] values = replaceSlavonic.values().toArray(new String[0]);
        return StringUtils.replaceEach(replaceIAndAddSolidMark(rus), keys, values);
    }

    private String replaceIAndAddSolidMark(String rus) {
        String oldSlavonic = "";
        char[] chRus = rus.toCharArray();
        for (int i = 0; i < chRus.length; i++) {
            if (chRus[i]=='и' && VOWELS.contains(String.valueOf(chRus[i+1]))){
                oldSlavonic += 'i';
            }
            else {
                oldSlavonic += chRus[i];
            }
            if (i == chRus.length - 1 || chRus[i + 1] == ' ' || chRus[i + 1] == '.' || chRus[i + 1] == ',') {
                if (CONSTANTS.contains(String.valueOf(chRus[i]))) {
                    oldSlavonic += 'ъ';
                }
            }
        }
        return oldSlavonic;
    }
}
